### PR TITLE
Make OS agnostic

### PR DESCRIPTION
**Pull request by patgmac**
Changed instances of “macOS Sierra” to $macOSname, which is specified
with $7 in the JSS.

### CODE REVIEW

**Comment by kc9wwh** [comment]
Hey @patgmac! 

Thanks for this. Just got back into the office and reviewing it everything looks good. My only concern is in the `heading` variable that we are calling the `macOSname` before it is declared. Did you notice any issues in this while testing?

Also, what are your thoughts on instead of declaring `macOSname` and `title` variables that we derive them from the `OSInstaller` variable?

**Comment by patgmac** [comment]
I did not have an issue referencing `macOSname` early since it's not actually being called upon yet. 

Getting `macOSname` and `title` from `OSInstaller` is not a bad idea. I'll see what I can do.

**Comment by patgmac** [comment]
@kc9wwh should be read to go now.

**Comment by kc9wwh** [comment]
Looks good, awesome work!

**Pull request merged**
