### PR TITLE
Create package_macOS

### PR DESCRIPTION
**Pull request by brodriguez255**

### CODE REVIEW

**Comment by kenchan0130** [comment]
Looks good!

I think it would be a good idea to properly reflect these in the "Staging the macOS Installer" item of README.md without separating the document.

**Comment by kc9wwh** [comment]
@brodriguez255 would you please submit an updated PR for these changes to be added to the README.md file instead? I do agree that we should keep these all in one place until we have time to build out the Wiki for this repo.

Thank you for your contribution!

**Comment by kenchan0130** [comment]
@brodriguez255  
Thank you for your contribution!
Please tell us the current status.

If there is no response, we will close this PR to prevent the stagnation of PR after the elapse of a certain period of time.

**Comment by taniguti** [comment]
Close this PR due to  merged #109.
Thanks you again for sending us this PR.

**Pull request closed without merging**
