### PR TITLE
Use existing OS installer

### PR DESCRIPTION
**Pull request by patgmac**
This allows use of existing Apple cached installer, and checks the
version. If the version is < $version, run $download_trigger.

### CODE REVIEW

**Comment by patgmac** [comment]
Hold off on this, found some problems. Working on them now.

**Comment by patgmac** [comment]
Ok, this should be ready now. Did test a few times, everything working good.

**Comment by patgmac** [comment]
Got it. Let me know how it looks. 

I think I added the --agreetolicense while troubleshooting something and forgot to removed it.

**Comment by kc9wwh** [comment]
Notes for me...

- Merge to v2.0
- Place note on release info of installer location change
- Need new screenshot from composer of cached installer
- Note custom trigger / cached policy in README
- Merge to Master

**Comment by patgmac** [comment]
How are we looking?

**Pull request merged**
